linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - ireturn
    - nlreturn
    - paralleltest
    - revive
    - varnamelen
    - wsl


linters-settings:
  cyclop:
    max-complexity: 11