linters:
  enable-all: false
  enable:
    - unparam
    - whitespace
    - unconvert
    - bodyclose
    - nakedret
    - prealloc
    - rowserrcheck
    - unconvert
    - gocritic
    - godox
    - errcheck
    - ineffassign

linters-settings:
  govet:
    check-shadowing: true
