version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - ireturn
    - nlreturn
    - paralleltest
    - revive
    - varnamelen
    - wsl
  settings:
    cyclop:
      max-complexity: 11
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
